version: 2
jobs:
  test-routine:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "tamuhack-site/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install tamuhack-site

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "tamuhack-site/package.json" }}

      # run tests!
      - run: cd tamuhack-site && npm test && cd ..
  build-routine:
    machine: true
    steps:
      - checkout
      - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run: docker build --rm=false -t gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1 .
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
  deploy-routine:
    machine: true
    working_directory: ~/repo
    steps:
      - run: ls
      - run: ./deploy.sh
workflows:
  version: 2
      - test-routine
      - build-routine:
          requires:
            - test-routine
      - deploy-routine:
          requires:
            - build-routine
                  


